# MySQL DataSource
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/queryopt?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true&rewriteBatchedStatements=true
    username: queryuser
    password: querypassword
    driverClassName: com.mysql.cj.jdbc.Driver
  # schema.sql을 사용하므로 JPA의 DDL 자동 생성 및 지연 초기화는 더 이상 필요하지 않습니다.
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: none # 스키마 관리는 schema.sql에 위임
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        # JDBC Batching 설정
        jdbc:
          batch_size: 50
          order_inserts: true
          order_updates: true
          batch_versioned_data: true
  # spring.jpa.defer-datasource-initialization: true # 더 이상 필요 없음
  sql:
    init:
      mode: always # 항상 schema.sql을 실행
