# MySQL DataSource
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/queryopt?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true&rewriteBatchedStatements=true
    username: queryuser
    password: querypassword
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: none # 스키마 관리는 schema.sql에 위임
    show-sql: true
    # properties 하위의 배치 관련 설정은 HibernateConfig.java에서 직접 하므로 제거합니다.
    properties:
      hibernate.format_sql: true
  sql:
    init:
      mode: always # 항상 schema.sql을 실행
